#!/usr/bin/env bash
# Bash script that displays domains and subdomains information

domain_information () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_information "www.$1" "www"
  domain_information "lb-01.$1" "lb-01"
  domain_information "web-01.$1" "web-01"
  domain_information "web-02.$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
