#!/usr/bin/env bash
# Install , configures

sudo apt-get update
sudo apt-get install -y nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

# To create directory if it doesn't exist
sudo mkdir -p /var/www/html

# change ownership for the directory for ease access
sudo chown -R 755 /var/www

# code to create index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# code to create webpage for 404 error
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the server
sudo service nginx restart
