#!/usr/bin/env bash
# installs, configures the haproxy

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend  kelvin-frontend
        bind *:80
        mode http
        default_backend kelvin-backend
backend kelvin-backend
        balance roundrobin
        server 100137-web-01 52.207.208.87:80 check
        server 100137-web-02 54.166.141.169:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
