#!/usr/bin/env bash
# A script that displays Best School 10 times using until loop
#   on the 9th iteration print Hi before Best School.

i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 9 ]
  then
    echo "Hi"	
  fi
  echo "Best School"
  (( i++ ))
done
