#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
# Allow TCP ports 22, 80 and 443.

sudo ufw version
sudo apt-get update
sudo apt-get install ufw
sudo ufw reset
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
sudo ufw status
